version: "3.9"

services:
  certbot:
    image: certbot/dns-cloudflare
    volumes:
      - certbot_etc:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cloudflare.ini:/root/cloudflare.ini
    command: >-
      certonly --dns-cloudflare
      --dns-cloudflare-credentials /root/cloudflare.ini
      --dns-cloudflare-propagation-seconds 60
      --email ${EMAIL_ADDRESS}
      --agree-tos --no-eff-email
      --force-renewal
      -d komodohype.dev
      -d *.komodohype.dev

  bulldog-tax:
    restart: unless-stopped
    build: ./bulldog-tax
    hostname: bulldog-tax
    depends_on:
      - redis
      - mongo
    volumes:
      - ./bulldog-tax/config.yaml:/app/config.yaml
  
  modlogs:
    restart: unless-stopped
    build: ./modlogs
    hostname: modlogs
    depends_on:
      - redis
      - mongo
    volumes:
      - ./modlogs/config.yaml:/app/config.yaml

  poll-api:
    restart: unless-stopped
    build: ./poll-api
    hostname: poll-api
    depends_on:
      - redis
      - mongo
    volumes:
      - ./poll-api/config.yaml:/app/config.yaml

  poll-frontend:
    restart: unless-stopped
    build: ./poll-frontend
    hostname: poll-frontend

  nginx:
    restart: unless-stopped
    build: ./nginx
    volumes:
      - certbot_etc:/etc/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 443:443
    depends_on:
      - poll-frontend
      - poll-api
      - modlogs
      - bulldog-tax

  mongo:
    restart: unless-stopped
    image: mongo:latest
    hostname: mongo
    volumes:
      - mongo_data:/data/db

  redis:
    restart: unless-stopped
    image: redis:latest
    hostname: redis
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  mongo_data:
  certbot_etc:
